"""create table birds

Revision ID: 72acd45c4d0f
Revises: 
Create Date: 2024-04-18 21:05:51.655248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72acd45c4d0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birds')
    # ### end Alembic commands ###
